# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxaPUt-wY3qyV_Cpu3qVw7Y_GZ0DDeCl
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Here is where I will config the Page
st.set_page_config(
    page_title="FEMA Disaster Relief Dashboard",
    layout="wide"
)

st.title("FEMA Disaster Relief Dashboard")
st.write("Exploring repair assistance and TSA eligibility for disaster survivors.")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("IndividualAssistanceHousingRegistrantsLargeDisasters (2).csv", low_memory=False)
    df["repairAmount"] = pd.to_numeric(df["repairAmount"], errors="coerce").fillna(0)
    df["tsaEligible"] = pd.to_numeric(df["tsaEligible"], errors="coerce")
    return df

df = load_data()

st.subheader("Data Preview")
st.write(df.head())

#I am adding simple filters in sidebar
st.sidebar.header("Filters")
state_filter = st.sidebar.multiselect(
    "Filter by state (damagedStateAbbreviation):",
    options=sorted(df["damagedStateAbbreviation"].dropna().unique()),
    default=None
)

if state_filter:
    df_plot = df[df["damagedStateAbbreviation"].isin(state_filter)].copy()
else:
    df_plot = df.copy()

st.markdown(
    f"Showing **{len(df_plot):,}** records "
    + ("for selected states." if state_filter else "from the full dataset.")
)

# Histogram of repairAmount:
st.subheader("Histogram of Repair Amount")

fig_hist = px.histogram(
    df_plot,
    x="repairAmount",
    nbins=30,
    title="Distribution of Repair Amounts",
    labels={"repairAmount": "Repair Amount (USD)"}
)
fig_hist.update_layout(margin=dict(l=20, r=20, t=40, b=20))

st.plotly_chart(fig_hist, use_container_width=True)

st.markdown(
    """
**Insight:** Most households have very low or zero recorded repair assistance,
with a small number receiving much larger amounts.
This right-skewed pattern matches the idea that only a subset of survivors qualify for substantial repair funding.
"""
)

# Boxplot of repairAmount by TSA eligibility:
st.subheader("Boxplot: Repair Amount by TSA Eligibility")

# Keep rows where tsaEligible is 0 or 1
df_box = df_plot[df_plot["tsaEligible"].isin([0, 1])].copy()
df_box["tsaEligibleLabel"] = df_box["tsaEligible"].map({0: "0 - Not Eligible", 1: "1 - Eligible"})

fig_box = px.box(
    df_box,
    x="tsaEligibleLabel",
    y="repairAmount",
    title="Repair Amount by TSA Eligibility",
    labels={
        "tsaEligibleLabel": "TSA Eligible (1 = Yes, 0 = No)",
        "repairAmount": "Repair Amount (USD)"
    }
)
fig_box.update_layout(margin=dict(l=20, r=20, t=40, b=20))

st.plotly_chart(fig_box, use_container_width=True)

st.markdown(
    """
**Insight:** TSA-eligible households tend to receive higher repair amounts
and show a wider spread in repair assistance than non-eligible households,
which is consistent with the statistical comparisons in the report.
"""
)


st.markdown("---")
st.markdown(
    "*This dashboard was created for the INFO 450 FEMA Disaster Relief project.  \
Use the state filter on the left to focus on specific affected areas.*"
)